# This is a basic workflow to help you get started with Actions

name: Build using Commands

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello Testing 1 2 3!
      

      - name: Docker Build
        run: docker build -t dipesh2301/flask_gitaction:latest .
        
      - name: DockerHub Login
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
        
      - name: Docker push 
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/flask_gitaction:latest 
       
        
